import { openai } from '@ai-sdk/openai'
import { generateObject } from 'ai'
import { NextResponse } from 'next/server'
import { z } from 'zod'

// Schema for the explanation response
const ExplanationSchema = z.object({
  summary: z.string().describe('A comprehensive summary of what this Salesforce object/page is used for'),
  purpose: z.string().describe('Brief one-line purpose statement'),
  field_explanations: z.array(
    z.object({
      field_name: z.string(),
      field_label: z.string(),
      field_type: z.string(),
      explanation: z.string(),
      tips: z.string().optional(),
    })
  ).describe('Explanations for common fields on this object'),
  related_processes: z.array(z.string()).describe('Common business processes related to this object'),
  best_practices: z.array(z.string()).describe('Best practices for working with this object'),
})

const SYSTEM_PROMPT = `You are Salesforce Buddy, an expert at explaining Salesforce objects and pages.
Your job is to help users understand what a Salesforce page/object is for and how to use it effectively.

When explaining a Salesforce object:
1. Provide a clear summary of the object's purpose
2. Explain the most important fields and what they're used for
3. List related business processes
4. Include practical tips for common tasks

Be concise but thorough. Assume the user is working in an enterprise environment with standard Salesforce objects.`

export async function POST(request: Request) {
  try {
    const { objectName, recordId, userRole } = await request.json()

    if (!objectName) {
      return NextResponse.json({ error: 'Object name is required' }, { status: 400 })
    }

    let contextPrompt = `Explain the Salesforce "${objectName}" object/page.`
    if (recordId) {
      contextPrompt += ` The user is viewing a specific record (ID: ${recordId}).`
    }
    if (userRole) {
      contextPrompt += ` The user's role is: ${userRole}. `
      if (userRole === 'intern') {
        contextPrompt += 'Provide more detailed explanations suitable for someone learning Salesforce.'
      } else if (userRole === 'lead') {
        contextPrompt += 'Focus on strategic insights and team management aspects.'
      }
    }

    const { object } = await generateObject({
      model: openai('gpt-4o-mini'),
      system: SYSTEM_PROMPT,
      prompt: contextPrompt,
      schema: ExplanationSchema,
    })

    // Transform into the expected response format
    const response = {
      object_name: objectName,
      object_label: objectName,
      record_id: recordId || null,
      summary: object.summary,
      purpose: object.purpose,
      field_explanations: object.field_explanations.map((field, index) => ({
        ...field,
        current_value: null, // No actual values since we don't have Salesforce connection
      })),
      related_processes: object.related_processes,
      sources_used: [
        {
          source_type: 'ai_generated',
          source_id: 0,
          title: 'AI-Generated Explanation',
          relevance_score: 0.9,
          snippet: 'Explanation generated by AI based on Salesforce best practices.',
        },
      ],
      safety_note: 'This explanation was generated by AI based on standard Salesforce knowledge. Organization-specific customizations may not be reflected.',
    }

    return NextResponse.json(response)
  } catch (error) {
    console.error('[v0] Error in explain API:', error)
    return NextResponse.json(
      { error: 'Failed to generate explanation' },
      { status: 500 }
    )
  }
}
