import { openai } from '@ai-sdk/openai'
import { generateText } from 'ai'
import { NextResponse } from 'next/server'

const SYSTEM_PROMPT = `You are Salesforce Buddy, an expert AI assistant for Salesforce users at an enterprise company. 
Your role is to help users understand Salesforce objects, fields, processes, and best practices.

Key responsibilities:
- Explain Salesforce concepts clearly and concisely
- Provide step-by-step guidance for common tasks
- Reference standard Salesforce terminology and best practices
- Help with case management, lead handling, opportunity tracking, and other CRM processes
- Provide actionable suggestions when appropriate

Response format:
- Use markdown formatting for clarity
- Use **bold** for important terms
- Use bullet points and numbered lists for steps
- Keep responses focused and practical
- If you're uncertain, acknowledge it and suggest alternatives

Context: You're helping users who work with Salesforce daily, ranging from interns learning the system to experienced leads managing teams.`

export async function POST(request: Request) {
  try {
    const { question, objectName, recordId, userRole } = await request.json()

    if (!question) {
      return NextResponse.json({ error: 'Question is required' }, { status: 400 })
    }

    // Build context based on available information
    let contextInfo = ''
    if (objectName) {
      contextInfo += `\nThe user is currently viewing a ${objectName} record.`
    }
    if (recordId) {
      contextInfo += ` Record ID: ${recordId}`
    }
    if (userRole) {
      contextInfo += `\nUser role: ${userRole}. Adjust detail level accordingly - interns need more explanation, leads need more strategic insights.`
    }

    const userPrompt = `${contextInfo ? `Context:${contextInfo}\n\n` : ''}Question: ${question}`

    const { text } = await generateText({
      model: openai('gpt-4o-mini'),
      system: SYSTEM_PROMPT,
      prompt: userPrompt,
      maxTokens: 1000,
    })

    // Parse the response into the expected format
    const response = {
      question,
      answer: text,
      confidence: 0.85,
      sources_used: [
        {
          source_type: 'ai_generated',
          source_id: 0,
          title: 'AI-Generated Response',
          relevance_score: 0.9,
          snippet: 'Response generated by AI based on Salesforce best practices.',
        },
      ],
      suggested_actions: extractSuggestedActions(text),
      safety_note: 'This response was generated by AI. Please verify critical information with official documentation or your team lead.',
      limitations: 'This is an AI-generated response. For organization-specific procedures, please consult your internal SOPs.',
    }

    return NextResponse.json(response)
  } catch (error) {
    console.error('[v0] Error in ask API:', error)
    return NextResponse.json(
      { error: 'Failed to generate response' },
      { status: 500 }
    )
  }
}

// Extract actionable items from the response
function extractSuggestedActions(text: string): string[] {
  const actions: string[] = []
  
  // Look for numbered steps or action items
  const stepMatches = text.match(/^\d+\.\s+(.+?)(?=\n|$)/gm)
  if (stepMatches && stepMatches.length > 0) {
    // Take first 3 steps as suggested actions
    stepMatches.slice(0, 3).forEach((match) => {
      const cleaned = match.replace(/^\d+\.\s+/, '').replace(/\*\*/g, '').trim()
      if (cleaned.length > 10 && cleaned.length < 100) {
        actions.push(cleaned)
      }
    })
  }

  // If no steps found, try to find action verbs
  if (actions.length === 0) {
    const actionPhrases = text.match(/(?:You should|Make sure to|Remember to|Be sure to|Consider)\s+([^.]+)/gi)
    if (actionPhrases) {
      actionPhrases.slice(0, 3).forEach((phrase) => {
        const cleaned = phrase.replace(/\*\*/g, '').trim()
        if (cleaned.length > 10 && cleaned.length < 100) {
          actions.push(cleaned)
        }
      })
    }
  }

  return actions.length > 0 ? actions : ['Review the answer and apply relevant steps']
}
