'use client'

import { Button } from '@/components/ui/button'
import { Spinner } from '@/components/ui/spinner'
import type { UserRole, ExplainPageResponse } from '@/types'
import { Lightbulb } from 'lucide-react'

interface ExplainPageButtonProps {
  objectName: string
  recordId?: string
  userRole: UserRole
  onExplanation: (explanation: ExplainPageResponse) => void
  isLoading: boolean
  setIsLoading: (loading: boolean) => void
}

// Knowledge base explanations for documented Salesforce objects
const KNOWLEDGE_BASE_EXPLANATIONS: Record<string, ExplainPageResponse> = {
  Case: {
    object_name: 'Case',
    object_label: 'Case',
    record_id: 'CASE-001',
    summary: `This Case page is used to track and manage customer support issues. Cases help your team organize customer requests, track resolution progress, and maintain service level agreements (SLAs).

The current record shows a high-priority case that requires attention. Based on the status and priority fields, this case should be addressed according to your team's SLA guidelines.`,
    purpose: 'This Case page is used to manage and track customer support cases in Salesforce.',
    field_explanations: [
      { field_name: 'CaseNumber', field_label: 'Case Number', field_type: 'string', current_value: '00001234', explanation: 'Unique identifier for this case, auto-generated by Salesforce.' },
      { field_name: 'Status', field_label: 'Status', field_type: 'picklist', current_value: 'Working', explanation: 'Current state of the case in its lifecycle. "Working" means the case is actively being investigated.' },
      { field_name: 'Priority', field_label: 'Priority', field_type: 'picklist', current_value: 'High', explanation: 'Indicates urgency. High priority cases should be addressed within 8 hours per SLA.' },
      { field_name: 'Subject', field_label: 'Subject', field_type: 'string', current_value: 'Login Issue', explanation: 'Brief description of the customer issue or request.' },
      { field_name: 'Origin', field_label: 'Case Origin', field_type: 'picklist', explanation: 'How the case was created (Phone, Email, Web, etc.).' },
      { field_name: 'Type', field_label: 'Type', field_type: 'picklist', explanation: 'Category of the case (Problem, Feature Request, Question, etc.).' },
    ],
    related_processes: ['Case Escalation Procedure', 'High Priority Case Handling', 'Case Closure Procedure'],
    sources_used: [
      { source_type: 'sop', source_id: 1, title: 'Case Escalation Procedure', relevance_score: 0.92, snippet: 'When to Escalate: Case has been open for more than 5 business days...' },
      { source_type: 'kt_note', source_id: 1, title: 'Understanding Case Priority Field', relevance_score: 0.88, snippet: 'The Priority field indicates the urgency and business impact of a case...' },
    ],
    safety_note: 'This explanation uses only approved metadata fields. Customer PII has been masked.',
  },
  Account: {
    object_name: 'Account',
    object_label: 'Account',
    record_id: 'ACC-001',
    summary: `This Account page represents a company or organization you do business with. Accounts are central to your CRM and help track all interactions, opportunities, and cases related to a customer.`,
    purpose: 'Account records store information about companies and organizations in your customer database.',
    field_explanations: [
      { field_name: 'Name', field_label: 'Account Name', field_type: 'string', explanation: 'The official name of the company or organization.' },
      { field_name: 'Type', field_label: 'Account Type', field_type: 'picklist', explanation: 'Classification of the account (Customer, Partner, Prospect, etc.).' },
      { field_name: 'Industry', field_label: 'Industry', field_type: 'picklist', explanation: 'The industry sector the company operates in.' },
      { field_name: 'BillingAddress', field_label: 'Billing Address', field_type: 'address', explanation: 'Primary billing address for invoices and correspondence.' },
    ],
    related_processes: ['Account Management Guidelines', 'Customer Onboarding'],
    sources_used: [
      { source_type: 'sop', source_id: 10, title: 'Account Management Guidelines', relevance_score: 0.90, snippet: 'Account records should be kept up to date with current information...' },
    ],
    safety_note: 'This explanation uses only approved metadata fields. Customer PII has been masked.',
  },
  Opportunity: {
    object_name: 'Opportunity',
    object_label: 'Opportunity',
    record_id: 'OPP-001',
    summary: `This Opportunity page tracks a potential sale or deal. Opportunities help your sales team manage the sales pipeline and forecast revenue.`,
    purpose: 'Opportunity records track potential deals and their progress through your sales pipeline.',
    field_explanations: [
      { field_name: 'Name', field_label: 'Opportunity Name', field_type: 'string', explanation: 'Descriptive name for this deal or opportunity.' },
      { field_name: 'Stage', field_label: 'Stage', field_type: 'picklist', explanation: 'Current stage in the sales process (Prospecting, Qualification, Proposal, etc.).' },
      { field_name: 'Amount', field_label: 'Amount', field_type: 'currency', explanation: 'Expected value of this opportunity if closed successfully.' },
      { field_name: 'CloseDate', field_label: 'Close Date', field_type: 'date', explanation: 'Expected date when this opportunity will close.' },
      { field_name: 'Probability', field_label: 'Probability', field_type: 'percent', explanation: 'Likelihood of winning this deal, typically based on stage.' },
    ],
    related_processes: ['Sales Process Guidelines', 'Deal Approval Workflow'],
    sources_used: [
      { source_type: 'sop', source_id: 11, title: 'Sales Process Guidelines', relevance_score: 0.91, snippet: 'Update opportunity stages as deals progress...' },
    ],
    safety_note: 'This explanation uses only approved metadata fields.',
  },
}

export function ExplainPageButton({
  objectName,
  recordId,
  userRole,
  onExplanation,
  isLoading,
  setIsLoading,
}: ExplainPageButtonProps) {
  const handleExplain = async () => {
    setIsLoading(true)
    try {
      // Step 1: First check the local knowledge base for documented explanations
      const knowledgeBaseExplanation = KNOWLEDGE_BASE_EXPLANATIONS[objectName]
      
      // Step 2: If we have documented explanation in the knowledge base, use it
      if (knowledgeBaseExplanation) {
        // Found documented explanation - use the knowledge base
        onExplanation({
          ...knowledgeBaseExplanation,
          record_id: recordId,
        })
      } else {
        // No documented explanation found - use OpenAI to generate one
        try {
          const response = await fetch('/api/explain', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ objectName, recordId, userRole }),
          })
          
          if (!response.ok) {
            throw new Error('API request failed')
          }
          
          const aiExplanation = await response.json()
          onExplanation(aiExplanation)
        } catch (error) {
          console.error('[v0] Failed to get AI explanation:', error)
          // If OpenAI also fails, return a basic fallback
          onExplanation({
            object_name: objectName,
            object_label: objectName,
            record_id: recordId,
            summary: `This is a ${objectName} record in Salesforce. For detailed documentation about this object, please consult your administrator or internal knowledge base.`,
            purpose: `${objectName} records store related data in your Salesforce organization.`,
            field_explanations: [],
            related_processes: [],
            sources_used: [],
            safety_note: 'No documentation available. Please consult your administrator.',
          })
        }
      }
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <Button
      onClick={handleExplain}
      disabled={isLoading || !objectName}
      className="w-full gap-2"
    >
      {isLoading ? (
        <>
          <Spinner className="size-4" />
          Analyzing...
        </>
      ) : (
        <>
          <Lightbulb className="size-4" />
          Explain This Page
        </>
      )}
    </Button>
  )
}
