'use client'

import { Button } from '@/components/ui/button'
import { Spinner } from '@/components/ui/spinner'
import { apiClient } from '@/lib/api-client'
import type { UserRole, ExplainPageResponse } from '@/types'
import { Lightbulb } from 'lucide-react'

interface ExplainPageButtonProps {
  objectName: string
  recordId?: string
  userRole: UserRole
  onExplanation: (explanation: ExplainPageResponse) => void
  isLoading: boolean
  setIsLoading: (loading: boolean) => void
}

// Mock explanation for demo
const MOCK_EXPLANATION: ExplainPageResponse = {
  object_name: 'Case',
  object_label: 'Case',
  record_id: 'CASE-001',
  summary: `This Case page is used to track and manage customer support issues. Cases help your team organize customer requests, track resolution progress, and maintain service level agreements (SLAs).

The current record shows a high-priority case that requires attention. Based on the status and priority fields, this case should be addressed according to your team's SLA guidelines.`,
  purpose: 'This Case page is used to manage and track customer support cases in Salesforce.',
  field_explanations: [
    { field_name: 'CaseNumber', field_label: 'Case Number', field_type: 'string', current_value: '00001234', explanation: 'Unique identifier for this case, auto-generated by Salesforce.' },
    { field_name: 'Status', field_label: 'Status', field_type: 'picklist', current_value: 'Working', explanation: 'Current state of the case in its lifecycle. "Working" means the case is actively being investigated.' },
    { field_name: 'Priority', field_label: 'Priority', field_type: 'picklist', current_value: 'High', explanation: 'Indicates urgency. High priority cases should be addressed within 8 hours per SLA.' },
    { field_name: 'Subject', field_label: 'Subject', field_type: 'string', current_value: 'Login Issue', explanation: 'Brief description of the customer issue or request.' },
    { field_name: 'Origin', field_label: 'Case Origin', field_type: 'picklist', explanation: 'How the case was created (Phone, Email, Web, etc.).' },
    { field_name: 'Type', field_label: 'Type', field_type: 'picklist', explanation: 'Category of the case (Problem, Feature Request, Question, etc.).' },
  ],
  related_processes: ['Case Escalation Procedure', 'High Priority Case Handling', 'Case Closure Procedure'],
  sources_used: [
    { source_type: 'sop', source_id: 1, title: 'Case Escalation Procedure', relevance_score: 0.92, snippet: 'When to Escalate: Case has been open for more than 5 business days...' },
    { source_type: 'kt_note', source_id: 1, title: 'Understanding Case Priority Field', relevance_score: 0.88, snippet: 'The Priority field indicates the urgency and business impact of a case...' },
  ],
  safety_note: 'This explanation uses only approved metadata fields. Customer PII has been masked.',
}

export function ExplainPageButton({
  objectName,
  recordId,
  userRole,
  onExplanation,
  isLoading,
  setIsLoading,
}: ExplainPageButtonProps) {
  const handleExplain = async () => {
    setIsLoading(true)
    try {
      // First try the backend API
      const explanation = await apiClient.explainPage(objectName, recordId, userRole)
      onExplanation(explanation)
    } catch {
      // If backend fails, use the local Next.js API route with OpenAI
      try {
        const response = await fetch('/api/explain', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ objectName, recordId, userRole }),
        })
        
        if (!response.ok) {
          throw new Error('API request failed')
        }
        
        const explanation = await response.json()
        onExplanation(explanation)
      } catch {
        // Final fallback to mock data if OpenAI also fails
        onExplanation({
          ...MOCK_EXPLANATION,
          object_name: objectName,
          object_label: objectName,
          record_id: recordId,
        })
      }
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <Button
      onClick={handleExplain}
      disabled={isLoading || !objectName}
      className="w-full gap-2"
    >
      {isLoading ? (
        <>
          <Spinner className="size-4" />
          Analyzing...
        </>
      ) : (
        <>
          <Lightbulb className="size-4" />
          Explain This Page
        </>
      )}
    </Button>
  )
}
